openapi: 3.0.0
info:
  version: 1.3.0
  title: Common Payment API
  license:
    name: Apache 2.0
paths:
  /standing-orders:
    post:
      parameters: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/standingorderSubmissionRequest'
      responses:
        '201':
          description: Created.
          headers: [ ]
        '400':
          $ref: '#/components/responses/standard400'
components:
  schemas:
    standingorderSubmissionRequest:
  responses:
    standard400: