/**
* Common Payment API
* This specification defines a simple payment API for payment types used in Switzerland.  The API is supposed to be used by customers who want to initiate a payment at their bank.  Note that, consents and SCA will be handled in a dedicated specification file. This specification uses schema definitions from the Common Data Model v1.2.1. 
*
* The version of the OpenAPI document: 1.3.0
* Contact: info@common-api.ch
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models


/**
 * 
 * @param instructionId 
 * @param statusCode 
 * @param reasonCode 
 * @param reasonInformation 
 */
data class PaymentInstructionItemStatus(
    val instructionId: kotlin.String,
    val statusCode: PaymentInstructionItemStatus.StatusCode,
    val reasonCode: kotlin.String? = null,
    val reasonInformation: kotlin.String? = null
) 
{
    /**
    * 
    * Values: aCCP,rJCT
    */
    enum class StatusCode(val value: kotlin.String){
        aCCP("ACCP"),
        rJCT("RJCT");
    }
}

