/**
* Common Payment API
* This specification defines a simple payment API for payment types used in Switzerland.  The API is supposed to be used by customers who want to initiate a payment at their bank.  Note that, consents and SCA will be handled in a dedicated specification file. This specification uses schema definitions from the Common Data Model v1.2.1. 
*
* The version of the OpenAPI document: 1.3.0
* Contact: info@common-api.ch
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models

import org.openapitools.server.models.PaymentCurrencyAmount
import org.openapitools.server.models.PaymentIBANDetail
import org.openapitools.server.models.PaymentISRDetail
import org.openapitools.server.models.PaymentIbanAccount
import org.openapitools.server.models.PaymentOtherDetail
import org.openapitools.server.models.PaymentQRDetail

/**
 * 
 * @param messageId 
 * @param initiatingPartyId 
 * @param debtorAccount 
 * @param instructionId 
 * @param endToEndId 
 * @param instructedAmount 
 * @param requestedExecutionDate 
 * @param ibanDetails 
 * @param isrDetails 
 * @param otherDetails 
 * @param qrDetails 
 */
data class SinglepaymentsSubmissionRequest(
    val messageId: kotlin.String,
    val initiatingPartyId: kotlin.String,
    val debtorAccount: PaymentIbanAccount,
    val instructionId: kotlin.String,
    val endToEndId: kotlin.String,
    val instructedAmount: PaymentCurrencyAmount,
    val requestedExecutionDate: java.time.LocalDate? = null,
    val ibanDetails: PaymentIBANDetail? = null,
    val isrDetails: PaymentISRDetail? = null,
    val otherDetails: PaymentOtherDetail? = null,
    val qrDetails: PaymentQRDetail? = null
) 

