/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * amount with currency
 *
 * @param currency ISO 4217 code
 * @param content amount given with fractional digits, the separator is a dot
 */


data class Amount (

    /* ISO 4217 code */
    @Json(name = "currency")
    val currency: kotlin.String,

    /* amount given with fractional digits, the separator is a dot */
    @Json(name = "content")
    val content: kotlin.String

)

