/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param code 
 * @param memberId 
 */


data class CommonClearingSystemMemberIdentification (

    @Json(name = "code")
    val code: kotlin.String,

    @Json(name = "memberId")
    val memberId: kotlin.String

)

