/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CommonErrorType

import com.squareup.moshi.Json

/**
 * 
 *
 * @param type 
 * @param title 
 * @param detail 
 * @param instance 
 */


data class CommonErrorResponse (

    @Json(name = "type")
    val type: CommonErrorType? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "detail")
    val detail: kotlin.String? = null,

    @Json(name = "instance")
    val instance: kotlin.String? = null

)

