/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * Error Types for commonErrorResponse.
 *
 * Values: iNVALIDPAYLOAD,mALFORMEDPAYLOAD,iNVALIDTOKEN,eXPIREDTOKEN,iNSUFFICIENTPRIVILEGES,nOACCESSTORESOURCE,rESOURCEDOESNOTEXIST,rESOURCENOTREADY,rESOURCETOOLARGE,wRONGMETHOD,oPERATIONNOTALLOWED,tECHNICALERROR,nOTIMPLEMENTED,sERVICEUNAVAILABLE
 */

enum class CommonErrorType(val value: kotlin.String) {

    @Json(name = "/problems/INVALID_PAYLOAD")
    iNVALIDPAYLOAD("/problems/INVALID_PAYLOAD"),

    @Json(name = "/problems/MALFORMED_PAYLOAD")
    mALFORMEDPAYLOAD("/problems/MALFORMED_PAYLOAD"),

    @Json(name = "/problems/INVALID_TOKEN")
    iNVALIDTOKEN("/problems/INVALID_TOKEN"),

    @Json(name = "/problems/EXPIRED_TOKEN")
    eXPIREDTOKEN("/problems/EXPIRED_TOKEN"),

    @Json(name = "/problems/INSUFFICIENT_PRIVILEGES")
    iNSUFFICIENTPRIVILEGES("/problems/INSUFFICIENT_PRIVILEGES"),

    @Json(name = "/problems/NO_ACCESS_TO_RESOURCE")
    nOACCESSTORESOURCE("/problems/NO_ACCESS_TO_RESOURCE"),

    @Json(name = "/problems/RESOURCE_DOES_NOT_EXIST")
    rESOURCEDOESNOTEXIST("/problems/RESOURCE_DOES_NOT_EXIST"),

    @Json(name = "/problems/RESOURCE_NOT_READY")
    rESOURCENOTREADY("/problems/RESOURCE_NOT_READY"),

    @Json(name = "/problems/RESOURCE_TOO_LARGE")
    rESOURCETOOLARGE("/problems/RESOURCE_TOO_LARGE"),

    @Json(name = "/problems/WRONG_METHOD")
    wRONGMETHOD("/problems/WRONG_METHOD"),

    @Json(name = "/problems/OPERATION_NOT_ALLOWED")
    oPERATIONNOTALLOWED("/problems/OPERATION_NOT_ALLOWED"),

    @Json(name = "/problems/TECHNICAL_ERROR")
    tECHNICALERROR("/problems/TECHNICAL_ERROR"),

    @Json(name = "/problems/NOT_IMPLEMENTED")
    nOTIMPLEMENTED("/problems/NOT_IMPLEMENTED"),

    @Json(name = "/problems/SERVICE_UNAVAILABLE")
    sERVICEUNAVAILABLE("/problems/SERVICE_UNAVAILABLE");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is CommonErrorType) "$data" else null

        /**
         * Returns a valid [CommonErrorType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): CommonErrorType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

