/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * The following codes from the EventFrequency7Code of ISO 20022 are supported. - Daily - Weekly - EveryTwoWeeks - Monthly - EveryTwoMonths - Quarterly - SemiAnnual - Annual 
 *
 * Values: daily,weekly,everyTwoWeeks,monthly,everyTwoMonths,quarterly,semiAnnual,annual
 */

enum class FrequencyCode(val value: kotlin.String) {

    @Json(name = "Daily")
    daily("Daily"),

    @Json(name = "Weekly")
    weekly("Weekly"),

    @Json(name = "EveryTwoWeeks")
    everyTwoWeeks("EveryTwoWeeks"),

    @Json(name = "Monthly")
    monthly("Monthly"),

    @Json(name = "EveryTwoMonths")
    everyTwoMonths("EveryTwoMonths"),

    @Json(name = "Quarterly")
    quarterly("Quarterly"),

    @Json(name = "SemiAnnual")
    semiAnnual("SemiAnnual"),

    @Json(name = "Annual")
    annual("Annual");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is FrequencyCode) "$data" else null

        /**
         * Returns a valid [FrequencyCode] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): FrequencyCode? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

