/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * links returned in the answer of an API call
 *
 * @param self 
 * @param first 
 * @param previous 
 * @param next 
 * @param last 
 */


data class Links (

    @Json(name = "self")
    val self: kotlin.String? = null,

    @Json(name = "first")
    val first: kotlin.String? = null,

    @Json(name = "previous")
    val previous: kotlin.String? = null,

    @Json(name = "next")
    val next: kotlin.String? = null,

    @Json(name = "last")
    val last: kotlin.String? = null

)

