/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param streetName 
 * @param postCode 
 * @param townName 
 * @param country 
 * @param buildingNumber 
 */


data class PaymentStructuredAddress (

    @Json(name = "streetName")
    val streetName: kotlin.String,

    @Json(name = "postCode")
    val postCode: kotlin.String,

    @Json(name = "townName")
    val townName: kotlin.String,

    @Json(name = "country")
    val country: kotlin.String,

    @Json(name = "buildingNumber")
    val buildingNumber: kotlin.String? = null

)

