/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Links
import org.openapitools.client.models.PaymentSubmissionRequest

import com.squareup.moshi.Json

/**
 * 
 *
 * @param paymentList 
 * @param links 
 */


data class PaymentsGet200Response (

    @Json(name = "paymentList")
    val paymentList: kotlin.collections.List<PaymentSubmissionRequest>? = null,

    @Json(name = "_links")
    val links: Links? = null

)

