/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param currency 
 * @param amount 
 */


data class PaymentCurrencyAmount (

    @Json(name = "currency")
    val currency: kotlin.String,

    @Json(name = "amount")
    val amount: kotlin.String

)

