/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.PaymentInstructionItemStatus

import com.squareup.moshi.Json

/**
 * 
 *
 * @param statusCode 
 * @param messageId 
 * @param transactions 
 */


data class PaymentSubmissionStatus (

    @Json(name = "statusCode")
    val statusCode: PaymentSubmissionStatus.StatusCode,

    @Json(name = "messageId")
    val messageId: kotlin.String? = null,

    @Json(name = "transactions")
    val transactions: kotlin.collections.List<PaymentInstructionItemStatus>? = null

) {

    /**
     * 
     *
     * Values: aCCP,rJCT,pART
     */
    enum class StatusCode(val value: kotlin.String) {
        @Json(name = "ACCP") aCCP("ACCP"),
        @Json(name = "RJCT") rJCT("RJCT"),
        @Json(name = "PART") pART("PART");
    }
}

