/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.PaymentBookingInstruction
import org.openapitools.client.models.PaymentIbanAccount
import org.openapitools.client.models.PaymentInstructionItem

import com.squareup.moshi.Json

/**
 * 
 *
 * @param messageId 
 * @param initiatingPartyId 
 * @param requestedExecutionDate 
 * @param debtorAccount 
 * @param bookingInstruction 
 * @param transactions 
 */


data class PaymentSubmissionRequest (

    @Json(name = "messageId")
    val messageId: kotlin.String,

    @Json(name = "initiatingPartyId")
    val initiatingPartyId: kotlin.String,

    @Json(name = "requestedExecutionDate")
    val requestedExecutionDate: java.time.LocalDate,

    @Json(name = "debtorAccount")
    val debtorAccount: PaymentIbanAccount,

    @Json(name = "bookingInstruction")
    val bookingInstruction: PaymentBookingInstruction,

    @Json(name = "transactions")
    val transactions: kotlin.collections.List<PaymentInstructionItem>

)

