/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CommonClearingSystemMemberIdentification

import com.squareup.moshi.Json

/**
 * 
 *
 * @param bic 
 * @param clearingSystemMemberIdentification 
 */


data class PaymentCreditorAgent (

    @Json(name = "bic")
    val bic: kotlin.String? = null,

    @Json(name = "clearingSystemMemberIdentification")
    val clearingSystemMemberIdentification: CommonClearingSystemMemberIdentification? = null

)

