/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.PaymentChargeBearerMethod
import org.openapitools.client.models.PaymentCreditor
import org.openapitools.client.models.PaymentCreditorAgent
import org.openapitools.client.models.PaymentOtherAccount
import org.openapitools.client.models.PaymentOtherRemittanceReference

import com.squareup.moshi.Json

/**
 * 
 *
 * @param creditorAccount 
 * @param creditorAgent 
 * @param creditor 
 * @param chargeBearer 
 * @param remittanceReference 
 */


data class PaymentOtherDetail (

    @Json(name = "creditorAccount")
    val creditorAccount: PaymentOtherAccount,

    @Json(name = "creditorAgent")
    val creditorAgent: PaymentCreditorAgent,

    @Json(name = "creditor")
    val creditor: PaymentCreditor,

    @Json(name = "chargeBearer")
    val chargeBearer: PaymentChargeBearerMethod? = null,

    @Json(name = "remittanceReference")
    val remittanceReference: PaymentOtherRemittanceReference? = null

)

