/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param instructionId 
 * @param statusCode 
 * @param reasonCode 
 * @param reasonInformation 
 */


data class PaymentInstructionItemStatus (

    @Json(name = "instructionId")
    val instructionId: kotlin.String,

    @Json(name = "statusCode")
    val statusCode: PaymentInstructionItemStatus.StatusCode,

    @Json(name = "reasonCode")
    val reasonCode: kotlin.String? = null,

    @Json(name = "reasonInformation")
    val reasonInformation: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: aCCP,rJCT
     */
    enum class StatusCode(val value: kotlin.String) {
        @Json(name = "ACCP") aCCP("ACCP"),
        @Json(name = "RJCT") rJCT("RJCT");
    }
}

