/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param addressLines max 2 lines of 70 characters
 * @param country 
 */


data class PaymentUnstructuredAddress (

    /* max 2 lines of 70 characters */
    @Json(name = "addressLines")
    val addressLines: kotlin.collections.List<kotlin.String>,

    @Json(name = "country")
    val country: kotlin.String

)

