/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param type IBAN or QR-IBAN of the creditor, only IBANs with CH or LI country code permitted.
 * @param identification 
 */


data class PaymentQrIbanAccount (

    /* IBAN or QR-IBAN of the creditor, only IBANs with CH or LI country code permitted. */
    @Json(name = "type")
    val type: PaymentQrIbanAccount.Type,

    @Json(name = "identification")
    val identification: kotlin.String

) {

    /**
     * IBAN or QR-IBAN of the creditor, only IBANs with CH or LI country code permitted.
     *
     * Values: iBAN,qRIBAN
     */
    enum class Type(val value: kotlin.String) {
        @Json(name = "IBAN") iBAN("IBAN"),
        @Json(name = "QR_IBAN") qRIBAN("QR_IBAN");
    }
}

