/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.PaymentCreditor
import org.openapitools.client.models.PaymentIsrRemittanceReference
import org.openapitools.client.models.PaymentOtherAccount

import com.squareup.moshi.Json

/**
 * 
 *
 * @param remittanceReference 
 * @param creditorAccount 
 * @param creditor 
 */


data class PaymentISRDetail (

    @Json(name = "remittanceReference")
    val remittanceReference: PaymentIsrRemittanceReference,

    @Json(name = "creditorAccount")
    val creditorAccount: PaymentOtherAccount? = null,

    @Json(name = "creditor")
    val creditor: PaymentCreditor? = null

)

