/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * either remittanceReference or remittanceInformation must be set
 *
 * @param type 
 * @param reference 
 */


data class PaymentOtherRemittanceReference (

    @Json(name = "type")
    val type: PaymentOtherRemittanceReference.Type? = null,

    @Json(name = "reference")
    val reference: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: sCOR
     */
    enum class Type(val value: kotlin.String) {
        @Json(name = "SCOR") sCOR("SCOR");
    }
}

