/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.PaymentStructuredOrUnstructuredAddress

import com.squareup.moshi.Json

/**
 * 
 *
 * @param name 
 * @param postalAddress 
 */


data class PaymentDebtor (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "postalAddress")
    val postalAddress: PaymentStructuredOrUnstructuredAddress

)

