/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.PaymentChargeBearerMethod
import org.openapitools.client.models.PaymentCreditor
import org.openapitools.client.models.PaymentCreditorAgent
import org.openapitools.client.models.PaymentIbanAccount
import org.openapitools.client.models.PaymentIbanRemittanceReference

import com.squareup.moshi.Json

/**
 * 
 *
 * @param creditorAccount 
 * @param creditor 
 * @param sepaIndicator 
 * @param creditorAgent 
 * @param chargeBearer 
 * @param remittanceReference 
 * @param remittanceInformation either remittanceReference or remittanceInformation must be set
 */


data class PaymentIBANDetail (

    @Json(name = "creditorAccount")
    val creditorAccount: PaymentIbanAccount,

    @Json(name = "creditor")
    val creditor: PaymentCreditor,

    @Json(name = "sepaIndicator")
    val sepaIndicator: kotlin.Boolean? = null,

    @Json(name = "creditorAgent")
    val creditorAgent: PaymentCreditorAgent? = null,

    @Json(name = "chargeBearer")
    val chargeBearer: PaymentChargeBearerMethod? = null,

    @Json(name = "remittanceReference")
    val remittanceReference: PaymentIbanRemittanceReference? = null,

    /* either remittanceReference or remittanceInformation must be set */
    @Json(name = "remittanceInformation")
    val remittanceInformation: kotlin.String? = null

)

