/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.PaymentCurrencyAmount
import org.openapitools.client.models.PaymentIBANDetail
import org.openapitools.client.models.PaymentISRDetail
import org.openapitools.client.models.PaymentOtherDetail
import org.openapitools.client.models.PaymentQRDetail

import com.squareup.moshi.Json

/**
 * 
 *
 * @param instructionId 
 * @param endToEndId 
 * @param instructedAmount 
 * @param ibanDetails 
 * @param isrDetails 
 * @param otherDetails 
 * @param qrDetails 
 */


data class PaymentInstructionItem (

    @Json(name = "instructionId")
    val instructionId: kotlin.String,

    @Json(name = "endToEndId")
    val endToEndId: kotlin.String,

    @Json(name = "instructedAmount")
    val instructedAmount: PaymentCurrencyAmount,

    @Json(name = "ibanDetails")
    val ibanDetails: PaymentIBANDetail? = null,

    @Json(name = "isrDetails")
    val isrDetails: PaymentISRDetail? = null,

    @Json(name = "otherDetails")
    val otherDetails: PaymentOtherDetail? = null,

    @Json(name = "qrDetails")
    val qrDetails: PaymentQRDetail? = null

)

