/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * Values: sINGLEBOOKINGSIA,sINGLEBOOKINGNOA,bATCHBOOKINGSALANOA,bATCHBOOKINGSALACND,bATCHBOOKINGNOA,bATCHBOOKINGCND,bATCHBOOKINGCWD
 */

enum class PaymentBookingInstruction(val value: kotlin.String) {

    @Json(name = "SINGLEBOOKING_SIA")
    sINGLEBOOKINGSIA("SINGLEBOOKING_SIA"),

    @Json(name = "SINGLEBOOKING_NOA")
    sINGLEBOOKINGNOA("SINGLEBOOKING_NOA"),

    @Json(name = "BATCHBOOKING_SALA_NOA")
    bATCHBOOKINGSALANOA("BATCHBOOKING_SALA_NOA"),

    @Json(name = "BATCHBOOKING_SALA_CND")
    bATCHBOOKINGSALACND("BATCHBOOKING_SALA_CND"),

    @Json(name = "BATCHBOOKING_NOA")
    bATCHBOOKINGNOA("BATCHBOOKING_NOA"),

    @Json(name = "BATCHBOOKING_CND")
    bATCHBOOKINGCND("BATCHBOOKING_CND"),

    @Json(name = "BATCHBOOKING_CWD")
    bATCHBOOKINGCWD("BATCHBOOKING_CWD");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PaymentBookingInstruction) "$data" else null

        /**
         * Returns a valid [PaymentBookingInstruction] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PaymentBookingInstruction? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

