/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.DayOfExecution
import org.openapitools.client.models.ExecutionRule
import org.openapitools.client.models.FrequencyCode
import org.openapitools.client.models.PaymentCurrencyAmount
import org.openapitools.client.models.PaymentIBANDetail
import org.openapitools.client.models.PaymentISRDetail
import org.openapitools.client.models.PaymentIbanAccount
import org.openapitools.client.models.PaymentOtherDetail
import org.openapitools.client.models.PaymentQRDetail
import org.openapitools.client.models.StandingorderSubmissionRequestExecutionBreaksInner

import com.squareup.moshi.Json

/**
 * 
 *
 * @param messageId 
 * @param initiatingPartyId 
 * @param debtorAccount 
 * @param instructionId 
 * @param endToEndId 
 * @param instructedAmount 
 * @param startDate The first applicable day of execution starting from this date is the first payment. 
 * @param frequency 
 * @param requestedExecutionDate 
 * @param ibanDetails 
 * @param isrDetails 
 * @param otherDetails 
 * @param qrDetails 
 * @param endDate The last applicable day of execution. If not given, it is an infinite standing order.
 * @param executionRule 
 * @param dayOfExecution 
 * @param executionMode The code of execution mode defines when or how standing order will be cancelled, processed the last time.   * UNTIL_DATE - standing order is valid until specific date - field endDate.  * UNTIL_CANCELLATION - standing order is valid forever and must be cancelled by client. 
 * @param executionBreaks List of break periods.
 */


data class StandingorderSubmissionRequest (

    @Json(name = "messageId")
    val messageId: kotlin.String,

    @Json(name = "initiatingPartyId")
    val initiatingPartyId: kotlin.String,

    @Json(name = "debtorAccount")
    val debtorAccount: PaymentIbanAccount,

    @Json(name = "instructionId")
    val instructionId: kotlin.String,

    @Json(name = "endToEndId")
    val endToEndId: kotlin.String,

    @Json(name = "instructedAmount")
    val instructedAmount: PaymentCurrencyAmount,

    /* The first applicable day of execution starting from this date is the first payment.  */
    @Json(name = "startDate")
    val startDate: java.time.LocalDate,

    @Json(name = "frequency")
    val frequency: FrequencyCode,

    @Json(name = "requestedExecutionDate")
    val requestedExecutionDate: java.time.LocalDate? = null,

    @Json(name = "ibanDetails")
    val ibanDetails: PaymentIBANDetail? = null,

    @Json(name = "isrDetails")
    val isrDetails: PaymentISRDetail? = null,

    @Json(name = "otherDetails")
    val otherDetails: PaymentOtherDetail? = null,

    @Json(name = "qrDetails")
    val qrDetails: PaymentQRDetail? = null,

    /* The last applicable day of execution. If not given, it is an infinite standing order. */
    @Json(name = "endDate")
    val endDate: java.time.LocalDate? = null,

    @Json(name = "executionRule")
    val executionRule: ExecutionRule? = null,

    @Json(name = "dayOfExecution")
    val dayOfExecution: DayOfExecution? = null,

    /* The code of execution mode defines when or how standing order will be cancelled, processed the last time.   * UNTIL_DATE - standing order is valid until specific date - field endDate.  * UNTIL_CANCELLATION - standing order is valid forever and must be cancelled by client.  */
    @Json(name = "executionMode")
    val executionMode: StandingorderSubmissionRequest.ExecutionMode? = null,

    /* List of break periods. */
    @Json(name = "executionBreaks")
    val executionBreaks: kotlin.collections.List<StandingorderSubmissionRequestExecutionBreaksInner>? = null

) {

    /**
     * The code of execution mode defines when or how standing order will be cancelled, processed the last time.   * UNTIL_DATE - standing order is valid until specific date - field endDate.  * UNTIL_CANCELLATION - standing order is valid forever and must be cancelled by client. 
     *
     * Values: dATE,cANCELLATION
     */
    enum class ExecutionMode(val value: kotlin.String) {
        @Json(name = "UNTIL_DATE") dATE("UNTIL_DATE"),
        @Json(name = "UNTIL_CANCELLATION") cANCELLATION("UNTIL_CANCELLATION");
    }
}

