/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 *
 *
 * @param validFromDate Start date of one break period. Standing order will not be processed from this date.  Date format YYYY-MM-DD.
 * @param validToDate End date of one break period. Standing order will not be processed to this date.  Date format YYYY-MM-DD.
 */


data class StandingorderSubmissionRequestExecutionBreaksInner(
    /* Start date of one break period. Standing order will not be processed from this date.  Date format YYYY-MM-DD.  */
    @Json(name = "validFromDate")
    val validFromDate: java.time.LocalDate? = null,

    /* End date of one break period. Standing order will not be processed to this date.  Date format YYYY-MM-DD.  */
    @Json(name = "validToDate")
    val validToDate: java.time.LocalDate? = null
)