/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import org.openapitools.client.models.CommonErrorResponse
import org.openapitools.client.models.StandingOrdersGet200Response
import org.openapitools.client.models.StandingorderSubmissionRequest
import org.openapitools.client.models.StandingorderSubmissionStatus

import org.openapitools.client.infrastructure.*
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import io.ktor.http.ParametersBuilder

    open class StandingOrdersApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
    ) : ApiClient(baseUrl, httpClientEngine, httpClientConfig, jsonBlock) {

        /**
        * Get the list of all standing orders.
        * Return the list of all standing orders for the authenticated context.
         * @param authorization Bearer followed by a base64 encoded OAuth access token 
         * @param xCorAPIClientID ID of the client forwarded to the provider. (SCOPE: FI) 
         * @param xCorrelationID Unique ID (defined by the caller) which will be reflected back in the response. 
         * @param userAgent Name and version of the of the Client software. 
         * @param xCorAPITargetID ID of the target, e.g., a financial institution. (SCOPE: FI - optional) (optional)
         * @param xPSUIPAddress IP address of the user initiating the operation (SCOPE: FI - optional) (optional)
         * @param xPSUUserAgent User of the client software (SCOPE: FI - optional) (optional)
         * @return StandingOrdersGet200Response
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun standingOrdersGet(authorization: kotlin.String, xCorAPIClientID: kotlin.String, xCorrelationID: kotlin.String, userAgent: kotlin.String, xCorAPITargetID: kotlin.String?, xPSUIPAddress: kotlin.String?, xPSUUserAgent: kotlin.String?): HttpResponse<StandingOrdersGet200Response> {

            val localVariableAuthNames = listOf<String>("OAuth2")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()
            authorization?.apply { localVariableHeaders["Authorization"] = this.toString() }
            xCorAPIClientID?.apply { localVariableHeaders["X-CorAPI-Client-ID"] = this.toString() }
            xCorrelationID?.apply { localVariableHeaders["X-Correlation-ID"] = this.toString() }
            userAgent?.apply { localVariableHeaders["User-Agent"] = this.toString() }
            xCorAPITargetID?.apply { localVariableHeaders["X-CorAPI-Target-ID"] = this.toString() }
            xPSUIPAddress?.apply { localVariableHeaders["X-PSU-IP-Address"] = this.toString() }
            xPSUUserAgent?.apply { localVariableHeaders["X-PSU-User-Agent"] = this.toString() }

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/standing-orders",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * Create a new Standing Order
        * It is used to create a permanent order for the transfer of funds.
         * @param authorization Bearer followed by a base64 encoded OAuth access token 
         * @param xCorAPIClientID ID of the client forwarded to the provider. (SCOPE: FI) 
         * @param xCorrelationID Unique ID (defined by the caller) which will be reflected back in the response. 
         * @param userAgent Name and version of the of the Client software. 
         * @param standingorderSubmissionRequest Details of standing orders submission to be added. 
         * @param xCorAPITargetID ID of the target, e.g., a financial institution. (SCOPE: FI - optional) (optional)
         * @param xPSUIPAddress IP address of the user initiating the operation (SCOPE: FI - optional) (optional)
         * @param xPSUUserAgent User of the client software (SCOPE: FI - optional) (optional)
         * @return void
        */
        open suspend fun standingOrdersPost(authorization: kotlin.String, xCorAPIClientID: kotlin.String, xCorrelationID: kotlin.String, userAgent: kotlin.String, standingorderSubmissionRequest: StandingorderSubmissionRequest, xCorAPITargetID: kotlin.String?, xPSUIPAddress: kotlin.String?, xPSUUserAgent: kotlin.String?): HttpResponse<Unit> {

            val localVariableAuthNames = listOf<String>("OAuth2")

            val localVariableBody = standingorderSubmissionRequest

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()
            authorization?.apply { localVariableHeaders["Authorization"] = this.toString() }
            xCorAPIClientID?.apply { localVariableHeaders["X-CorAPI-Client-ID"] = this.toString() }
            xCorrelationID?.apply { localVariableHeaders["X-Correlation-ID"] = this.toString() }
            userAgent?.apply { localVariableHeaders["User-Agent"] = this.toString() }
            xCorAPITargetID?.apply { localVariableHeaders["X-CorAPI-Target-ID"] = this.toString() }
            xPSUIPAddress?.apply { localVariableHeaders["X-PSU-IP-Address"] = this.toString() }
            xPSUUserAgent?.apply { localVariableHeaders["X-PSU-User-Agent"] = this.toString() }

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/standing-orders",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * Delete a specific standing order submission
        * Delete a specific standing order submission.
         * @param submissionID ID of payment submission to be retrieved. 
         * @param authorization Bearer followed by a base64 encoded OAuth access token 
         * @param xCorAPIClientID ID of the client forwarded to the provider. (SCOPE: FI) 
         * @param xCorrelationID Unique ID (defined by the caller) which will be reflected back in the response. 
         * @param userAgent Name and version of the of the Client software. 
         * @param xCorAPITargetID ID of the target, e.g., a financial institution. (SCOPE: FI - optional) (optional)
         * @param xPSUIPAddress IP address of the user initiating the operation (SCOPE: FI - optional) (optional)
         * @param xPSUUserAgent User of the client software (SCOPE: FI - optional) (optional)
         * @return void
        */
        open suspend fun standingOrdersSubmissionIdDelete(submissionID: kotlin.String, authorization: kotlin.String, xCorAPIClientID: kotlin.String, xCorrelationID: kotlin.String, userAgent: kotlin.String, xCorAPITargetID: kotlin.String?, xPSUIPAddress: kotlin.String?, xPSUUserAgent: kotlin.String?): HttpResponse<Unit> {

            val localVariableAuthNames = listOf<String>("OAuth2")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()
            authorization?.apply { localVariableHeaders["Authorization"] = this.toString() }
            xCorAPIClientID?.apply { localVariableHeaders["X-CorAPI-Client-ID"] = this.toString() }
            xCorrelationID?.apply { localVariableHeaders["X-Correlation-ID"] = this.toString() }
            userAgent?.apply { localVariableHeaders["User-Agent"] = this.toString() }
            xCorAPITargetID?.apply { localVariableHeaders["X-CorAPI-Target-ID"] = this.toString() }
            xPSUIPAddress?.apply { localVariableHeaders["X-PSU-IP-Address"] = this.toString() }
            xPSUUserAgent?.apply { localVariableHeaders["X-PSU-User-Agent"] = this.toString() }

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/standing-orders/{submissionId}".replace("{" + "Submission ID" + "}", "$submissionID"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * Get a specific standing order submission
        * Retrieve a specific standing order submission.
         * @param submissionID ID of payment submission to be retrieved. 
         * @param authorization Bearer followed by a base64 encoded OAuth access token 
         * @param xCorAPIClientID ID of the client forwarded to the provider. (SCOPE: FI) 
         * @param xCorrelationID Unique ID (defined by the caller) which will be reflected back in the response. 
         * @param userAgent Name and version of the of the Client software. 
         * @param xCorAPITargetID ID of the target, e.g., a financial institution. (SCOPE: FI - optional) (optional)
         * @param xPSUIPAddress IP address of the user initiating the operation (SCOPE: FI - optional) (optional)
         * @param xPSUUserAgent User of the client software (SCOPE: FI - optional) (optional)
         * @return StandingorderSubmissionRequest
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun standingOrdersSubmissionIdGet(submissionID: kotlin.String, authorization: kotlin.String, xCorAPIClientID: kotlin.String, xCorrelationID: kotlin.String, userAgent: kotlin.String, xCorAPITargetID: kotlin.String?, xPSUIPAddress: kotlin.String?, xPSUUserAgent: kotlin.String?): HttpResponse<StandingorderSubmissionRequest> {

            val localVariableAuthNames = listOf<String>("OAuth2")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()
            authorization?.apply { localVariableHeaders["Authorization"] = this.toString() }
            xCorAPIClientID?.apply { localVariableHeaders["X-CorAPI-Client-ID"] = this.toString() }
            xCorrelationID?.apply { localVariableHeaders["X-Correlation-ID"] = this.toString() }
            userAgent?.apply { localVariableHeaders["User-Agent"] = this.toString() }
            xCorAPITargetID?.apply { localVariableHeaders["X-CorAPI-Target-ID"] = this.toString() }
            xPSUIPAddress?.apply { localVariableHeaders["X-PSU-IP-Address"] = this.toString() }
            xPSUUserAgent?.apply { localVariableHeaders["X-PSU-User-Agent"] = this.toString() }

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/standing-orders/{submissionId}".replace("{" + "Submission ID" + "}", "$submissionID"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * Get status information for the specific standing order submission
        * Retrieve a specific standing order submission&#39;s status.
         * @param submissionID ID of payment submission to be retrieved. 
         * @param authorization Bearer followed by a base64 encoded OAuth access token 
         * @param xCorAPIClientID ID of the client forwarded to the provider. (SCOPE: FI) 
         * @param xCorrelationID Unique ID (defined by the caller) which will be reflected back in the response. 
         * @param userAgent Name and version of the of the Client software. 
         * @param xCorAPITargetID ID of the target, e.g., a financial institution. (SCOPE: FI - optional) (optional)
         * @param xPSUIPAddress IP address of the user initiating the operation (SCOPE: FI - optional) (optional)
         * @param xPSUUserAgent User of the client software (SCOPE: FI - optional) (optional)
         * @return StandingorderSubmissionStatus
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun standingOrdersSubmissionIdStatusGet(submissionID: kotlin.String, authorization: kotlin.String, xCorAPIClientID: kotlin.String, xCorrelationID: kotlin.String, userAgent: kotlin.String, xCorAPITargetID: kotlin.String?, xPSUIPAddress: kotlin.String?, xPSUUserAgent: kotlin.String?): HttpResponse<StandingorderSubmissionStatus> {

            val localVariableAuthNames = listOf<String>("OAuth2")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()
            authorization?.apply { localVariableHeaders["Authorization"] = this.toString() }
            xCorAPIClientID?.apply { localVariableHeaders["X-CorAPI-Client-ID"] = this.toString() }
            xCorrelationID?.apply { localVariableHeaders["X-Correlation-ID"] = this.toString() }
            userAgent?.apply { localVariableHeaders["User-Agent"] = this.toString() }
            xCorAPITargetID?.apply { localVariableHeaders["X-CorAPI-Target-ID"] = this.toString() }
            xPSUIPAddress?.apply { localVariableHeaders["X-PSU-IP-Address"] = this.toString() }
            xPSUUserAgent?.apply { localVariableHeaders["X-PSU-User-Agent"] = this.toString() }

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/standing-orders/{submissionId}/status".replace("{" + "Submission ID" + "}", "$submissionID"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        }
